#!/bin/bash
echo "🔧 Validation complète MongoDB + GitHub Actions"
echo "=============================================="

URI="mongodb+srv://mhd:mohamed@cluster0.8dlnbfe.mongodb.net/gestion_scolaire?retryWrites=true&w=majority"

echo ""
echo "1. ✅ Votre URI MongoDB :"
echo "   $URI"
echo ""
echo "2. 📋 Pour GitHub Secrets :"
echo "   • Nom: MONGODB_URI"
echo "   • Valeur: $URI"
echo ""
echo "3. 🔐 Autres secrets nécessaires :"
echo "   • AWS_ACCESS_KEY_ID: AKIA... (votre clé AWS)"
echo "   • AWS_SECRET_ACCESS_KEY: wJalr... (votre secret AWS)"
echo "   • JWT_SECRET: $(openssl rand -hex 32)"
echo "   • EB_APPLICATION: gestion-scolaire"
echo ""
echo "4. 🚀 Prochaines étapes :"
echo "   a. Ajouter tous les secrets sur GitHub"
echo "   b. git add . && git commit -m 'Add MongoDB config'"
echo "   c. git push origin main"
echo "   d. Surveiller : https://github.com/mhdgeek/gestion-scolaire-sn/actions"
echo ""
echo "5. 🔍 Monitoring :"
echo "   Une fois déployé, testez :"
echo "   curl https://votre-app.elasticbeanstalk.com/health"
