AWSTemplateFormatVersion: '2010-09-09'
Description: 'Réseau VPC sécurisé pour l application de gestion scolaire'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VPC'
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PublicSubnet1'
Outputs:
  VpcId:
    Description: ID du VPC créé
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
